.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH RDDT 1 "July 2001"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
rddt \- GoldEd+ route diagram drawing tool
.SH SYNOPSIS
.B rddt
.RI < routefile "> [" "address or name" ]
.SH DESCRIPTION
This manual page documents briefly the command line parameters of
.BR rddt ,
the route diagram drawing tool for GoldEd+.
.\" This manual page was written for the Debian GNU/Linux distribution
.\" because the original program does not have a manual page.
.\" Instead, it has documention-in-progress that is copied to the
.\" /usr/share/doc/goldedplus directory.
.PP
Rddt reads the output of GoldEd+'s READmakepathreport function.
.SH OPTIONS
.TP
.B -D
Reserved for debugging purposes.
.TP
.BI -I n
Sets indent to
.IR n .
.TP
.BI -L "link_address"
This option used to specify your link address. Requires option
.BR -N .
.TP
.BI -N "address"
Use this option to specify your address.
.TP
.B -P
Decode path.
.SH EXAMPLE
.B RDDT path.rpt -n2:5020/604.19 -l2:5020/604 2:5020/604.19 -p
.SH SEE ALSO
.BR golded (1).
.SH AUTHOR
GoldEd is copyright (C) 1990-1999 Odinn Sorensen
.PP
GoldEd+ is copyright (C) 1999-2001 Alexander S. Aganichev
.PP
This manual page was written by peter karlsson
